### ISSUE TITLE
There was something wrong with the set_scale and set_settings methods of the SceneItem class defined in pyslobs/slobs/scenenode.py.

### ISSUE THREAD

**Issue by UnkoMamire** [Julian-O/PySLOBS#3]
The first argument of both is not named "self".

**Comment by Julian-O** [comment]
Thanks for bringing this to my attention, and also the pull request.

This note is just to reassure you I am not ignoring this. I am on it, and hope to release a fixed version soon.

I have reviewed the code looking for other instances of the same mistake, and found none.

This is in an area that hasn't been covered by "testing" (I have been using the expression 'exercising' because it isn't true testing.) I am working on writing some new test cases, and in doing so, identified a few other localised issues, which I want to release fixes for in the same release.

**Comment by Julian-O** [comment]
I have release 1.2.0.

It includes this fix.
It includes test code to exercise this area.
It fixes a large number of bugs found while doing so.
